// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bento: dynamic(() => import("./Bento")),
  biography: dynamic(() => import("./Biography")),
  call_to_action: dynamic(() => import("./CallToAction")),
  content_index: dynamic(() => import("./ContentIndex")),
  experience: dynamic(() => import("./Experience")),
  expertise: dynamic(() => import("./Expertise")),
  hero: dynamic(() => import("./Hero")),
  rich_text: dynamic(() => import("./RichText")),
  showcase: dynamic(() => import("./Showcase")),
  skills: dynamic(() => import("./Skills")),
  social: dynamic(() => import("./Social")),
  // tech_list: dynamic(() => import("./TechList")),
  text_block: dynamic(() => import("./TextBlock")),
};
